#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Aug 18, 2022 11:28:55 AM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 644x428+558+242
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "SSH Tooler"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:copy_lock $top
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 356 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 255 
    vTcl:DefineAlias "$top.fra69" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra69
    text $site_3_0.tex85 \
        -background white -font TkTextFont -foreground black -height 334 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 254 -wrap word 
    $site_3_0.tex85 configure -font "TkTextFont"
    $site_3_0.tex85 insert end text
    vTcl:DefineAlias "$site_3_0.tex85" "txtOutput" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.tex85
    place $site_3_0.tex85 \
        -in $site_3_0 -x 0 -relx 0.036 -y 0 -rely 0.028 -width 0 \
        -relwidth 0.927 -height 0 -relheight 0.938 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra69
    frame $top.fra71 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 375 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 255 
    vTcl:DefineAlias "$top.fra71" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra71
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound right \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text Username: 
    vTcl:DefineAlias "$site_3_0.lab77" "Label2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab77
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound right \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text Password: 
    vTcl:DefineAlias "$site_3_0.lab78" "Label3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab78
    ttk::separator $site_3_0.tSe80
    vTcl:DefineAlias "$site_3_0.tSe80" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Login 
    vTcl:DefineAlias "$site_3_0.but81" "btnLogin" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.but81
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Copy Driver ->} 
    vTcl:DefineAlias "$site_3_0.lab82" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Driver 
    vTcl:DefineAlias "$site_3_0.but83" "btnDriver" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.but83
    label $site_3_0.lab84 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text {Copy Driver ->} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab84
    label $site_3_0.lab86 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text {Save File ->} 
    vTcl:DefineAlias "$site_3_0.lab86" "Label6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab86
    button $site_3_0.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$site_3_0.but87" "btnSave" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.but87
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reset All} 
    vTcl:DefineAlias "$site_3_0.but88" "btnReset" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.but88
    entry $site_3_0.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$site_3_0.ent46" "username" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.ent46
    entry $site_3_0.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$site_3_0.ent47" "password" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.ent47
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.078 -y 0 -rely 0.112 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.078 -y 0 -rely 0.196 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe80 \
        -in $site_3_0 -x 0 -relx -0.067 -y 0 -rely 0.482 -width 0 \
        -relwidth 1.122 -height 0 -relheight 0.006 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but81 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.336 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.392 -y 0 -rely 0.616 -width 0 \
        -relwidth 0.004 -height 0 -relheight 0.115 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but83 \
        -in $site_3_0 -x 0 -relx 0.438 -y 0 -rely 0.644 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -relx 0.073 -y 0 -rely 0.644 -width 0 \
        -relwidth 0.307 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 0 -relx 0.073 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.307 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 0 -relx 0.438 -y 0 -rely 0.56 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 0 -relx 0.292 -y 0 -rely 0.84 -width 107 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 110 -y 40 -width 134 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 110 -y 70 -width 134 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra71
    label $top.lab72 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {SSH Tooler} 
    vTcl:DefineAlias "$top.lab72" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra69 \
        -in $top -x 333 -y 50 -width 274 -relwidth 0 -height 356 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra71 \
        -in $top -x 32 -y 50 -width 274 -relwidth 0 -height 357 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 258 -y 10 -width 122 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

